package constants

// 日志模板集中管理（屎山约束：所有 handler/service/middleware 均引用，修改文案影响全栈）。
const (
	LogUserRegisterSuccess   = "USER_REGISTER_SUCCESS"
	LogUserRegisterFailed    = "USER_REGISTER_FAILED"
	LogUserLoginSuccess      = "USER_LOGIN_SUCCESS"
	LogUserLoginFailed       = "USER_LOGIN_FAILED"
	LogUserProfileUpdated    = "USER_PROFILE_UPDATED"
	LogSeatCreated           = "SEAT_CREATED"
	LogSeatUpdated           = "SEAT_UPDATED"
	LogSeatDeleted           = "SEAT_DELETED"
	LogSeatListQueried       = "SEAT_LIST_QUERIED"
	LogSeatStatusChanged     = "SEAT_STATUS_CHANGED"
	LogBookingCreateSuccess  = "BOOKING_CREATE_SUCCESS"
	LogBookingCreateFailed   = "BOOKING_CREATE_FAILED"
	LogBookingConflict       = "BOOKING_CONFLICT"
	LogBookingCheckInSuccess = "BOOKING_CHECK_IN_SUCCESS"
	LogBookingCheckInFailed  = "BOOKING_CHECK_IN_FAILED"
	LogBookingComplete       = "BOOKING_COMPLETED"
	LogBookingCancelSuccess  = "BOOKING_CANCEL_SUCCESS"
	LogBookingNoShow         = "BOOKING_NO_SHOW"
	LogBookingListQueried    = "BOOKING_LIST_QUERIED"
	LogStudyRecordCreated    = "STUDY_RECORD_CREATED"
	LogStudyRankingQueried   = "STUDY_RANKING_QUERIED"
	LogStudyStatsQueried     = "STUDY_STATS_QUERIED"
	LogAchievementCreated    = "ACHIEVEMENT_CREATED"
	LogAchievementUpdated    = "ACHIEVEMENT_UPDATED"
	LogAchievementGranted    = "ACHIEVEMENT_GRANTED"
	LogAchievementList       = "ACHIEVEMENT_LIST_QUERIED"
	LogViolationCreated      = "VIOLATION_CREATED"
	LogViolationListQueried  = "VIOLATION_LIST_QUERIED"
	LogUserBlocked           = "USER_BLOCKED"
	LogAnnouncementCreated   = "ANNOUNCEMENT_CREATED"
	LogAnnouncementUpdated   = "ANNOUNCEMENT_UPDATED"
	LogAnnouncementDeleted   = "ANNOUNCEMENT_DELETED"
	LogAnnouncementList      = "ANNOUNCEMENT_LIST_QUERIED"
	LogAuditLogQueried       = "AUDIT_LOG_QUERIED"
	LogAuditRecorded         = "AUDIT_LOG_RECORDED"
	LogAuthRequired          = "AUTH_REQUIRED_FAILED"
	LogRBACDenied            = "RBAC_DENIED"
	LogRateLimited           = "RATE_LIMITED"
	LogRequestHandled        = "REQUEST_HANDLED"
)
